/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-09-01

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/


//Includes
#include "stm32f4xx.h"
#define ARM_MATH_CM4
/*#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"*/

/* Private macro */
/* Private variables */
/* Private function prototypes */
void GPIO__Init(void);
void TIM2_Init(void);
void PWM (uint32_t value);
void TIM4_ms_Delay(uint32_t delay);

/* Private functions */
void GPIO__Init(void)
{
    RCC->AHB1ENR |= 1; //Enable GPIOA clock
    GPIOA->AFR[0] |= 0x00100000; // Select the PA5 pin in alternate function mode
    GPIOA->MODER |= 0x00000800; //Set the PA5 pin alternate function
}



void TIM2_Init()
{

	//Steps
//	Set clock Enable
	// set prescaler frequency
	//set Total period of cycle
//	Set the PWM mode
	//Enable your channel "channel 1"
	// initialize the first duty cycle
    RCC->APB1ENR |=1;
    TIM2->PSC = 16-1; //Setting the clock frequency to 1MHz.
    TIM2->ARR = 20000; // Total period of the timer
    TIM2->CNT = 0;
    TIM2->CCMR1 = 0x0060; //PWM mode for the timer
    TIM2->CCER |= 1; //Enable channel 1 as output
    TIM2->CCR1 = 0; // initialize by 0 duty cycle
}

void PWM (uint32_t value)
{
 TIM2->CCR1 = value;  //Make the developer control it voltage

}


void TIM4_ms_Delay(uint32_t delay)
{
    RCC->APB1ENR |= 1<<2; //Start the clock for the timer peripheral
    TIM4->PSC = 16000-1; //Setting the clock frequency to 1kHz.
    TIM4->ARR = (delay); // Total period of the timer
    TIM4->CNT = 0;
    TIM4->CR1 |= 1; //Start the Timer
    while(!(TIM4->SR & TIM_SR_UIF)){} //Polling the update interrupt flag
    TIM4->SR &= ~(0x0001); //Reset the update interrupt flag
}



/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


int main()
{
    RCC->CFGR |= 0<<10; // set APB1 = 16 MHz
    GPIO__Init();
    TIM2_Init();
    TIM2->CR1 |= 1;
    while(1)
    {

     	PWM (15000); //75% From total cycle

    }
    return 0;
}


